=== RhinoLance/figaro-community/figaro-tools/schemas/figaro-ftd.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://figaro.conryclan.com/schema/figaro-ftd.schema.json",
  "title": "Figaro Task Definition",
  "description": "Schema for Figaro task definition JSON files.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "title",
    "description",
    "script",
    "autoRunOnConnect",
    "autoRunPriority",
    "autoLock",
    "runLocked"
  ],
  "properties": {
    "title": {
      "type": "string",
      "minLength": 1,
      "maxLength": 120
    },
    "description": {
      "type": "string",
      "maxLength": 1000
    },
    "script": {
      "type": "string",
      "minLength": 1
    },
    "color": {
      "type": "string",
      "pattern": "^#[0-9a-fA-F]{6}$"
    },
    "autoRunOnConnect": {
      "type": "boolean"
    },
    "autoRunPriority": {
      "type": "integer",
      "minimum": 0,
      "maximum": 999
    },
    "autoLock": {
      "type": "boolean"
    },
    "runLocked": {
      "type": "boolean"
    }
  }
}

=== RhinoLance/figaro-community/script-library/multiSwrCheck.json
{
  "title": "Multi SWR check",
  "description": "Check the SWR for a set of frequencies",
  "script": "const FREQ_LIST = [\r\n\t7032000,\r\n\t14044000,\r\n\t21044000\r\n];\r\n\r\nconst MMINDEX_MAX_PA_V = 'MMProtection|Max. PA voltage';\r\nconst MMINDEX_SWR_PROTECTION = 'MMProtection|SWR protection';\r\nconst PA_V_TUNE = 4.50;\r\nconst PA_V_OPERATE = 11.5;\r\n\r\nconsole.log(\"Multi SWR Check\");\r\n\r\nlet vfo, mode, power, swrProtection;\r\n\r\nconst saveSettings = async () => {\r\n\t\r\n\t/*\r\n\t0-10 digits: IF frequency in Hz\r\n\t11-16 N/A (Spaces)\r\n\t17-22 RIT offset in Hz (signed)\r\n\t23 RIT status (0=off, 1=on)\r\n\t24 XIT status (0=off, 1=on)\r\n\t25-27 N/A\r\n\t28 TX Status (0=RX, 1=TX)\r\n\t29 MODE\r\n\t30 RX VFO (0=A, 1=B)\r\n\t31 N/A\r\n\t32 Split status (0=off, 1=on)\r\n\t33-34 N/A\r\n\t35 N/A (Space)\r\n\t*/\r\n\r\n\tconst rawIF = await sendCat(`IF;`);\r\n\tvfo = rawIF.substring(30,31) == \"0\" ? \"A\" : \"B\";\r\n\tmode = rawIF.substring(29,30);\r\n\r\n\tpower = (await sendCat(`${MMINDEX_MAX_PA_V};`)).substring(2);\r\n\tswrProtection = (await sendCat(`${MMINDEX_SWR_PROTECTION};`)).substring(2);\r\n\t//console.log(`SWR Protection saving state: ${swrProtection}`);\r\n\r\n}\r\n\r\nconst revertSettings = async () => {\r\n\tsendCat(`MD${mode};`, false);\r\n\tsendCat(`${MMINDEX_MAX_PA_V}=${PA_V_OPERATE};`, false);\r\n\tsendCat(`${MMINDEX_SWR_PROTECTION}=${swrProtection};`, false);\r\n\t\r\n\t//console.log(`SWR Protection reverting to: ${swrProtection}`);\r\n\r\n\t//let tmp = (await sendCat(`${MMINDEX_SWR_PROTECTION};`)).substring(2);\r\n\r\n\t//console.log(`SWR Protection saved: ${tmp}`);\r\n};\r\n\r\nconst getSWR = async () => {\r\n\t\r\n\tconst resultList = [];\r\n\tfor( let cI=0; cI<10; cI++) {\r\n\t\tconst raw = (await sendCat('SW;')).substring(2);\r\n\t\tlet val = raw / 100;\r\n\t\tresultList.push(val);\r\n\t}\r\n\r\n\tconst sum = resultList.reduce((acc, value) => acc + value, 0);\r\n\r\n\tconst avg = sum/10;\r\n\treturn avg.toFixed(1);\r\n};\r\n\r\nconst setBand = (freq) => {\r\n\tconst band = Math.floor(freq / 1000000);\r\n\treturn `${band} MHz`;\r\n};\r\n\r\nconst tuneSetup = async () => {\r\n\tawait saveSettings();\r\n\t\r\n\tsendCat(`${MMINDEX_MAX_PA_V}=${PA_V_TUNE};`, false);\r\n\tsendCat(`${MMINDEX_SWR_PROTECTION}=DISABLED;`, false);\r\n\tsendCat('MD6;', false); // FSK\r\n\r\n\t//let tmp = (await sendCat(`${MMINDEX_SWR_PROTECTION};`)).substring(2);\r\n\r\n\t//console.log(`SWR Protection set for tune: ${tmp}`);\r\n};\r\n\r\nconst txStart = () => {\r\n\tsendCat('TX;', false);\r\n\tsendCat('TA500;', false);\r\n\tdelay(6);\r\n};\r\n\r\nconst txStop = () => {\r\n\tsendCat('TA0;', false);\r\n\tdelay(6);\r\n\tsendCat('RX;', false);\r\n}\r\n\r\nconst freqList = FREQ_LIST;\r\n\r\nawait tuneSetup();\r\n\r\nsetDescription( \"Checking ...\" );\r\n\r\nconst swrList = [];\r\n\r\nfor( const freq of freqList ) {\r\n\tawait sendCat(`F${vfo}${freq};`, false);\r\n\tawait txStart();\r\n\tawait delay(100);\r\n\tconst swr = await getSWR();\r\n\tswrList.push({freq, swr });  \r\n\tawait txStop();\t\r\n}\r\n\r\nawait revertSettings();\r\n\r\nlet output = swrList.map( v=> {\r\n\treturn `${Math.round(v.freq/100)/10}: ${v.swr}`\r\n})\r\n.join(\" | \");\r\n\r\nsetDescription( output );",
  "autoRunOnConnect": false,
  "autoRunPriority": 0,
  "autoLock": false,
  "runLocked": false
}

=== RhinoLance/figaro-community/script-library/cycle-agc.json
{
  "title": "Cycle AGC presets",
  "description": "",
  "script": "console.log(\"Cycle AGC script loaded\");\r\n\r\n/*\r\n\r\nMost details taken from \r\nhttps://groups.io/g/QRPLabs/topic/best_qmx_agc_settings/110439092\r\n\r\n*/\r\n\r\nconst AGC_LIST = [\r\n\t{\r\n\t\tname: \"QMX Default\",\r\n\t\tattribution: \"QRP Labs\",\r\n\t\tthresholdS: 8,\r\n\t\tslopeDbPerDb: 80,\r\n\t\tnoiseFilter: 10,\r\n\t\thangTime: 80,\r\n\t\tsmoothSamples: 50,\r\n\t\trecoveryDbPerSecond: 10,\r\n\t\tsampleBlocks: 2,\r\n\t\terrors: \"locked x1\"\r\n\t},\r\n\t{\r\n\t\tname: \"Baloo\",\r\n\t\tattribution: \"Rick - W5NR\",\r\n\t\tthresholdS: 7,\r\n\t\tslopeDbPerDb: 60,\r\n\t\tnoiseFilter: 5,\r\n\t\thangTime: 30,\r\n\t\tsmoothSamples: 50,\r\n\t\trecoveryDbPerSecond: 50,\r\n\t\tsampleBlocks: 2\r\n\t},\r\n\t{\r\n\t\tname: \"Gadget\",\r\n\t\tattribution: \"Dan - W2DLC\",\r\n\t\tthresholdS: 8,\r\n\t\tslopeDbPerDb: 65,\r\n\t\tnoiseFilter: 9,\r\n\t\thangTime: 55,\r\n\t\tsmoothSamples: 60,\r\n\t\trecoveryDbPerSecond: 8,\r\n\t\tsampleBlocks: 2\r\n\t},\r\n\t{\r\n\t\tname: \"Granny\",\r\n\t\tattribution: \"Ron\",\r\n\t\tthresholdS: 7,\r\n\t\tslopeDbPerDb: 95,\r\n\t\tnoiseFilter: 5,\r\n\t\thangTime: 50,\r\n\t\tsmoothSamples: 99,\r\n\t\trecoveryDbPerSecond: 40,\r\n\t\tsampleBlocks: 4\r\n\t},\r\n\t{\r\n\t\tname: \"Paddington\",\r\n\t\tattribution: \"K7VIQ\",\r\n\t\tthresholdS: 8,\r\n\t\tslopeDbPerDb: 80,\r\n\t\tnoiseFilter: 10,\r\n\t\thangTime: 80,\r\n\t\tsmoothSamples: 50,\r\n\t\trecoveryDbPerSecond: 10,\r\n\t\tsampleBlocks: 2\r\n\t},\r\n\t{\r\n\t\tname: \"Pingu\",\r\n\t\tattribution: \"Other\",\r\n\t\tthresholdS: 7,\r\n\t\tslopeDbPerDb: 60,\r\n\t\tnoiseFilter: 5,\r\n\t\thangTime: 30,\r\n\t\tsmoothSamples: 50,\r\n\t\trecoveryDbPerSecond: 50,\r\n\t\tsampleBlocks: 4\r\n\t},\r\n\t{\r\n\t\tname: \"Taz\",\r\n\t\tattribution: \"Steve - G4EDG\",\r\n\t\tthresholdS: 4,\r\n\t\tslopeDbPerDb: 50,\r\n\t\tnoiseFilter: 0,\r\n\t\thangTime: 2,\r\n\t\tsmoothSamples: 0,\r\n\t\trecoveryDbPerSecond: 60,\r\n\t\tsampleBlocks: 2,\r\n\t\terrors: \"locked x2\"\r\n\t},\r\n\t{\r\n\t\tname: \"Tom\",\r\n\t\tattribution: \"Chuck - WA3UQV\",\r\n\t\tthresholdS: 12,\r\n\t\tslopeDbPerDb: 80,\r\n\t\tnoiseFilter: 10,\r\n\t\thangTime: 80,\r\n\t\tsmoothSamples: 50,\r\n\t\trecoveryDbPerSecond: 10,\r\n\t\tsampleBlocks: 2\r\n\t},\r\n\t{\r\n\t\tname: \"Tweety\",\r\n\t\tattribution: \"KL7MJ\",\r\n\t\tthresholdS: 4,\r\n\t\tslopeDbPerDb: 80,\r\n\t\tnoiseFilter: 10,\r\n\t\thangTime: 30,\r\n\t\tsmoothSamples: 50,\r\n\t\trecoveryDbPerSecond: 10,\r\n\t\tsampleBlocks: 2\r\n\t},\r\n\t{\r\n\t\tname: \"User Defined 1\",\r\n\t\tattribution: \"\",\r\n\t\tthresholdS: 8,\r\n\t\tslopeDbPerDb: 80,\r\n\t\tnoiseFilter: 10,\r\n\t\thangTime: 80,\r\n\t\tsmoothSamples: 50,\r\n\t\trecoveryDbPerSecond: 10,\r\n\t\tsampleBlocks: 5\r\n\t},\r\n\r\n];\r\n\r\nconst getNext = (lastIndex, list) => {\r\n\tlet index = isNaN(lastIndex) ? -1 : lastIndex;\r\n\tindex = (index + 1) % list.length;\r\n\treturn index;\r\n};\r\n\r\nconst applyAGCSettings = (settings) => {\r\n\tconst prefix = \"MMAUDIO|AGC settings|\";\r\n\r\n\tsendCat(`${prefix}Threshold S=${settings.thresholdS};`, false);\r\n\tsendCat(`${prefix}Slope dB per dB=${settings.slopeDbPerDb};`, false);\r\n\tsendCat(`${prefix}Noise filter=${settings.noiseFilter};`, false);\r\n\tsendCat(`${prefix}Hang time=${settings.hangTime};`, false);\r\n\tsendCat(`${prefix}Smooth samples=${settings.smoothSamples};`, false);\r\n\tsendCat(`${prefix}Recovery db/s=${settings.recoveryDbPerSecond};`, false);\r\n\tsendCat(`${prefix}Sample blocks=${settings.sampleBlocks};`, false);\r\n};\r\n\r\n\r\nconst loadAGCSettingsFromRadio = async () => {\r\n\ttry {\r\n\t\tconst settings = {};\r\n\t\tconst prefix = \"MMAUDIO|AGC settings|\";\r\n\t\tsettings.thresholdS = await sendCat(`${prefix}Threshold S;`);\r\n\t\tsettings.slopeDbPerDb = await sendCat(`${prefix}Slope dB per dB;`);\r\n\t\tsettings.noiseFilter = await sendCat(`${prefix}Noise filter;`);\r\n\t\tsettings.hangTime = await sendCat(`${prefix}Hang time;`);\r\n\t\tsettings.smoothSamples = await sendCat(`${prefix}Smooth samples;`);\r\n\t\tsettings.recoveryDbPerSecond = await sendCat(`${prefix}Recovery db/s;`);\r\n\t\tsettings.sampleBlocks = await sendCat(`${prefix}Sample blocks;`);\r\n\t\tsettings.s9SoundsLikeS = await sendCat(`${prefix}S9 sounds like S;`);\r\n\t\treturn settings;\r\n\t}\r\n\tcatch (e) {\r\n\t\tconsole.error(\"Error loading AGC settings from radio:\", e);\r\n\t\treturn null;\r\n\t}\r\n};\r\n\r\nconst getDescriptionMarker = (activeIndex, length) => {\r\n\r\n\tlet out = \"\";\r\n\r\n\tfor (let i = 0; i < AGC_LIST.length; i++) {\r\n\t\tout += (i == activeIndex ? \"^\" : \"-\");\r\n\t}\r\n\r\n\treturn out;\r\n};\r\n\r\nconst formatSettings = (settings) => {\r\n\r\n\tlet out = \"\";\r\n\r\n\tObject.entries(settings).forEach(([key, value]) => {\r\n\t\tout += `${key}:\\t${value}\\n`;\r\n\t});\r\n\r\n\treturn out;\r\n};\r\n\r\nconst getVersionInfo = async () => {\r\n\tconst fwVersion = await sendCat(\"VN;\");\r\n\tconst verParts = fwVersion.match(/\\d+/g).map(Number);\r\n\r\n\treturn {\r\n\t\tmajor: parseInt(verParts[0]),\r\n\t\tminor: parseInt(verParts[1]),\r\n\t\tpatch: parseInt(verParts[2])\r\n\t}\r\n};\r\n\r\ntry{ \r\n\tconst lastIndex = parseInt(Storage.get(\"lastIndex\"));\r\n\tconst index = getNext(lastIndex, AGC_LIST);\r\n\tStorage.set(\"lastIndex\", index);\r\n\r\n\tconst settings = AGC_LIST[index];\r\n\tapplyAGCSettings(settings);\r\n\r\n\tsetTitle(`${context.task.title}: [${settings.name}]`);\r\n\t\r\n\tconst versionInfo = await getVersionInfo();\r\n\tlet versionWarning = \"\";\r\n\tif( versionInfo.minor >= 4 ){\r\n\t\tawait sendCat(\"MU;\");\r\n\t}\r\n\telse{\r\n\t\tversionWarning = \"Note: AGC settings may not apply until radio is restarted or \" + \r\n\t\t\t\t\"menu is entered and exited.  Update to firmware v1.04 \" + \r\n\t\t\t\t\"or later to load automatically.\";\r\n\t}\r\n\r\n\tconst activeMarker = getDescriptionMarker(index, AGC_LIST.length);\r\n\tconst formattedSettings = formatSettings(settings);\r\n\t\r\n\tsetDescription(`${context.task.description} ${activeMarker}\\n` + \r\n\t\t`${formattedSettings}\\n\\n${versionWarning}`);\r\n\r\n}\r\ncatch (e) {\r\n\tconsole.error(\"Error applying AGC settings:\", e);\r\n\tsetDescription(`${context.task.description}\\nError applying AGC settings: ${e.message}`);\r\n}",
  "autoRunOnConnect": false,
  "autoRunPriority": 0,
  "autoLock": false,
  "runLocked": false,
  "color": "#22c55e"
}

=== RhinoLance/figaro-community/script-library/scan.json
{
  "title": "Scan",
  "description": "Scan the current band",
  "script": "console.log(\"scan script loaded\");\r\n\r\nconst FREQ_STEP = 100; // 100Hz step, adjust as needed\r\nconst SCAN_SPEED = 100; // 100ms between frequency changes, adjust as needed\r\nconst TX_MONITOR_INTERVAL = 100; // 100ms between TX status checks, adjust as needed\r\nconst STOP_ON_TX = true; // stop scanning when transmission is detected\r\n\r\nlet freq =0;\r\nlet vfo;\r\nlet scanActive = false;\r\n\r\nlet scanTimerId;\r\nlet txMonitorTimerId;\r\n\r\nlet resume;\r\n\r\nconst getState = () => {\r\n\r\n\treturn sendCat(\"IF;\")\r\n\t\t.then( status => {\r\n\r\n\t\t\tconst regex = /IF(\\d{11}).{17}(\\d)/;\r\n\t\t\tconst match = status.match(regex);\r\n\r\n\t\t\tif (match) {\r\n\t\t\t\tfreq = parseInt(match[1]);\r\n\t\t\t\tvfo = parseInt(match[2]) == 0 ? \"A\" : \"B\";\r\n\t\t\t\tlog(`IF: ${freq} Hz, VFO: ${vfo}`);\r\n\r\n\t\t\t} else {\r\n\t\t\t\tlog(\"Failed to parse IF status\");\r\n\t\t\t}\r\n\r\n\t\t\treturn true;\r\n\r\n\t\t});\r\n\r\n};\r\n\r\nconst setNextFreq = () => {\r\n\tfreq = freq + FREQ_STEP;\r\n\tsendCat(`F${vfo}${freq};`, false);\r\n};\r\n\r\nconst scan = () => {\r\n\t\r\n\tif( !scanActive ) {\r\n\t\treturn;\r\n\t}\r\n\r\n\tsetNextFreq();\r\n\t\r\n\t// Use recursive setTimeout to mitigate slower devices not keeping up \r\n\t// with the scan speed when using setInterval\r\n\tscanTimerId = task.setTimeout(() => {\r\n\t\tscan();\r\n\t}, SCAN_SPEED);\r\n};\r\n\r\nconst monitorTx = () => {\r\n\t\r\n\tconst checkTxStatus = () => {\r\n\t\tsendCat(\"TQ;\").then( status => {\r\n\t\t\tif( status.substring(2) === \"1\") {\r\n\t\t\t\tlog(\"Transmission detected, stopping scan\");\r\n\t\t\t\tresume();\r\n\t\t\t\tcancelScan();\r\n\t\t\t}\r\n\r\n\t\t\tif (scanActive) {\r\n\t\t\t\ttxMonitorTimerId = task.setTimeout(checkTxStatus, \r\n\t\t\t\t\tTX_MONITOR_INTERVAL);\r\n\t\t\t}\r\n\t\t});\r\n\t};\r\n\t\r\n\tcheckTxStatus();\r\n};\r\n\r\nconst cancelScan = () => {\r\n\tscanActive = false;\r\n\ttask.clearTimeout(scanTimerId);\r\n\ttask.clearTimeout(txMonitorTimerId);\r\n}\r\n\r\nconst runner = Promise.resolve()\r\n\t.then( getState )\r\n\t.then( () => { if (STOP_ON_TX) monitorTx(); } )\r\n\t.then( ()=> {\r\n\t\tscanActive = true;\r\n\t\tscan();\r\n\r\n\t\tconst cancelPromise = new Promise((resolve) => {\r\n\t\t\tresume = resolve;\r\n\t\t});\r\n\r\n\t\treturn pause('stop', '', cancelPromise);\r\n\t})\r\n\t.finally( ()=> {\r\n\t\tcancelScan();\r\n\t});\r\n\t\r\n\ttask.waitUntil(runner);",
  "autoRunOnConnect": false,
  "autoRunPriority": 0,
  "autoLock": false,
  "runLocked": false
}

=== RhinoLance/figaro-community/script-library/agc-tune-s9SoundsLike.json
{
  "title": "AGC tune \"S9 sounds like\"",
  "description": "",
  "script": "const name = \"S9 sounds like\"\r\nconst catSuffix = \"S9 sounds like S\";\r\nconst valuePrefix = \"S\";\r\nconst range = [0,12];\r\nconst step = 1;\r\n\r\nconsole.log(`AGC tune ${name} script loaded`);\r\n\r\nconst LIST = Array.from({ length: Math.floor((range[1] - range[0]) / step) + 1 }, (_, i) => i * step + range[0]);\r\n\r\nconst getNext = (lastIndex, list) => {\r\n\tlet index = isNaN(lastIndex) ? -1 : lastIndex;\r\n\tindex = (index + 1) % list.length;\r\n\treturn index;\r\n}\r\n\r\nconst applyAGCSettings = (value) => {\r\n\tconst prefix = \"MMAUDIO|AGC settings|\";\r\n\r\n\tsendCat(`${prefix}${catSuffix}=${value};`, false);\r\n}\r\n\r\nconst getDescription = (activeIndex, length) => {\r\n\t\r\n\tlet out = \"\";\r\n\r\n\tfor( let i=0; i<LIST.length; i++) {\r\n\t\tout += (i == activeIndex ? \"^\" : \"-\");\r\n\t}\r\n\r\n\treturn out;\r\n}\r\n\r\nconst lastIndex = parseInt(Storage.get(\"lastIndex\"));\r\nconst index = getNext(lastIndex, LIST);\r\nStorage.set(\"lastIndex\", index);\r\n\r\napplyAGCSettings(LIST[index]);\r\n\r\nsetTitle(`${context.task.title}: ${valuePrefix}${LIST[index]}`);\r\nconst description = getDescription(index, LIST.length);\r\nsetDescription(`${context.task.description} ${description}`);",
  "autoRunOnConnect": false,
  "autoRunPriority": 0,
  "autoLock": false,
  "runLocked": false,
  "color": "#22c55e"
}

=== RhinoLance/figaro-community/script-library/tune.json
{
  "title": "Tune mode",
  "description": "Transmit a low powered carrier and display the SWR",
  "script": "console.log(\"Tune script\");\r\n\r\nlet interval, freq, vfo, mode, power, vol, dispFreq, swrProtection;\r\n\r\nconst saveSettings = async () => {\r\n\t/*\r\n\r\n\tIF\r\n\t00021044020     +00000000006000000 \r\n\t00021044020\r\n\t-----\r\n\t+0000\r\n\t0000006000000 \r\n\t\r\n\t0-10 digits: IF frequency in Hz\t\t\t00021044020\r\n\t11-15 N/A (Spaces)\t\t\t\t\t\t-----\r\n\t16-20 RIT offset in Hz (signed)\t\t\t+0000\r\n\t21 RIT status (0=off, 1=on)\t\t \t\r\n\t22 XIT status (0=off, 1=on)\r\n\t23-25 N/A\r\n\t26 TX Status (0=RX, 1=TX)\r\n\t27 MODE\r\n\t28 RX VFO (0=A, 1=B)\r\n\t29 N/A\r\n\t30 Split status (0=off, 1=on)\r\n\t31-32 N/A\r\n\t33 N/A (Space)\r\n\t*/\r\n\r\n\tconst rawIF = (await sendCat(`IF;`)).substring(2);\r\n\tfreq = rawIF.substring(0,10);\r\n\tvfo = rawIF.substring(28,29) == \"0\" ? \"A\" : \"B\";\r\n\tmode = rawIF.substring(27,28);\r\n\r\n\tconsole.log(`Saved settings - Freq: ${freq}, VFO: ${vfo}, Mode: ${mode}`);\r\n}\r\n\r\nconst revertSettings = () => {\r\n\tsendCat(`MD${mode};`, false);\r\n};\r\n\r\nconst printSWR = async () => {\r\n\tconst raw = (await sendCat('SW;')).substring(2);\r\n\tlet val = raw / 100;\r\n\tprint( `${dispFreq}\\n${val.toFixed(1)}` );\r\n};\r\n\r\nconst getBand = (freq) => {\r\n\tconst band = Math.floor(freq / 100000);\r\n\treturn `${band} MHz`;\r\n};\r\n\r\nconst tuneSetup = async () => {\r\n\tawait saveSettings();\r\n};\r\n\r\nconst tuneStart = () => {\r\n\tsendCat('MD8;', false); // SWR\r\n};\r\n\r\nconst tuneStop = async () => {\r\n\tsendCat(`MD${mode};`, false);\r\n}\r\n\r\nconst tuneTeardown = () => {\r\n\ttask.clearInterval(interval);\r\n\trevertSettings();\r\n};\r\n\r\nawait tuneSetup();\r\n\r\ndispFreq = getBand(freq);\r\ninterval = task.setInterval(printSWR, 500);\r\n\r\nawait tuneStart();\r\nawait pause('stop', '#D63031');\r\nawait tuneStop();\r\n\r\ntuneTeardown();",
  "autoRunOnConnect": false,
  "autoRunPriority": 0,
  "autoLock": false,
  "runLocked": false
}

=== RhinoLance/figaro-community/script-library/swr-tune-quick.json
{
  "title": "Tune SWR - Quick",
  "description": "Displays the SWR for several frequencies in one go.",
  "script": "console.log(\"Multi SWR Check\");\r\n\r\nconst FREQ_SRC = \"SCRIPT\"; // MSG | SCRIPT\r\nconst MESSAGE_INDEX = 10;\r\nconst FREQ_LIST = [\r\n\t7032000,\r\n\t14044000,\r\n\t21044000\r\n];\r\n\r\nconst getFreqList = async () => {\r\n\t\r\n\tswitch (FREQ_SRC) {\r\n\t\tcase \"MSG\":\r\n\t\t\treturn await getFreqListFromMessage(MESSAGE_INDEX);\r\n\t\tcase \"SCRIPT\":\r\n\t\t\treturn FREQ_LIST;\r\n\t\tdefault:\r\n\t\t\tthrow new Error(`Invalid FREQ_SRC: ${FREQ_SRC}`);\r\n\t}\r\n}\r\n\r\nconst getFreqListFromMessage = async (index) => {\r\n\t\r\n\tconst raw = (await sendCat(`MMMessages|Message ${index};`)).substring(2);\r\n\treturn raw.split('|')\r\n\t\t.map(f => f.trim())\r\n\t\t.filter(f => /^\\d+$/.test(f));\r\n}\r\n\r\nconst saveSettings = async () => {\r\n\t\r\n\t/*\r\n\t0-10 digits: IF frequency in Hz\r\n\t11-16 N/A (Spaces)\r\n\t17-22 RIT offset in Hz (signed)\r\n\t23 RIT status (0=off, 1=on)\r\n\t24 XIT status (0=off, 1=on)\r\n\t25-27 N/A\r\n\t28 TX Status (0=RX, 1=TX)\r\n\t29 MODE\r\n\t30 RX VFO (0=A, 1=B)\r\n\t31 N/A\r\n\t32 Split status (0=off, 1=on)\r\n\t33-34 N/A\r\n\t35 N/A (Space)\r\n\t*/\r\n\r\n\tconst rawIF = await sendCat(`IF;`);\r\n\tfreq = rawIF.substring(2,13);\r\n\tvfo = rawIF.substring(30,31) == \"0\" ? \"A\" : \"B\";\r\n\tmode = rawIF.substring(29,30);\r\n\r\n\tconsole.log(`Saved settings - Freq: ${freq}, VFO: ${vfo}, Mode: ${mode}`);\r\n}\r\n\r\nconst getFirmwareVersion = async () => {\r\n\tconst versionText = await sendCat(\"VN;\");  // 1_04_003QMX;\r\n\tconst parts = versionText.split(\"_\");\r\n\tconst major = parseInt(parts[0].substring(2));\r\n\tconst minor = parseInt(parts[1]);\r\n\tconst patch = parseInt(parts[2].substring(0,3));\r\n\r\n\treturn [major,minor,patch];\r\n}\r\n\r\nconst isFirmwareOk = (fwVersion, checkVersion) => {\r\n\r\n\tconst invalidCheckVersion = () => {\r\n\t\tconsole.error( `Invalid firmware check version: ${checkVersion}`)\r\n\t};\r\n\r\n\tif( checkVersion.length < 3){\r\n\t\tinvalidCheckVersion();\r\n\t}\r\n\r\n\tfor( let cI=0; cI<fwVersion.length; cI++ ) {\r\n\t\tif( isNaN(checkVersion[cI])) {\r\n\t\t\tinvalidCheckVersion();\r\n\t\t}\r\n\t\tif( fwVersion[cI] < checkVersion[cI] ) return false;\r\n\t}\r\n\r\n\treturn true;\r\n}\r\n\r\nconst revertSettings = async () => {\r\n\tsendCat(`MD${mode};`, false);\r\n\tsendCat(`F${vfo}${freq};`, false);\r\n};\r\n\r\nconst getSWR = async () => {\r\n\t\r\n\tconst resultList = [];\r\n\tfor( let cI=0; cI<10; cI++) {\r\n\t\tconst raw = (await sendCat('SW;')).substring(2);\r\n\t\tlet val = raw / 100;\r\n\t\tresultList.push(val);\r\n\t}\r\n\r\n\tconst sum = resultList.reduce((acc, value) => acc + value, 0);\r\n\r\n\tconst avg = sum/10;\r\n\treturn avg.toFixed(1);\r\n};\r\n\r\nconst setBand = (freq) => {\r\n\tconst band = Math.floor(freq / 1000000);\r\n\treturn `${band} MHz`;\r\n};\r\n\r\nconst tuneSetup = async () => {\r\n\tawait saveSettings();\r\n};\r\n\r\nconst txStart = () => {\r\n\tsendCat('MD8;', false); // SWR\r\n};\r\n\r\nconst txStop = () => {\r\n\tsendCat(`MD${mode};`, false);\r\n}\r\n\r\nconst prerunCheck = async () => {\r\n\r\n\tconst fwVersion = await getFirmwareVersion();\r\n\tconst reqFw = [1,4,3];\r\n\tif( !isFirmwareOk(fwVersion, reqFw)) {\r\n\t\tsetDescription(\"ERROR: This script requires firmware >= \" + \r\n\t\t\treqFw.join(\".\"));\r\n\t\treturn false;\r\n\t}\r\n\r\n\treturn true;\r\n\r\n}\r\n\r\nlet freq, vfo, mode, power;\r\n\r\nif( !(await prerunCheck())) return;\r\n\r\nconst freqList = await getFreqList();\r\n\r\nawait tuneSetup();\r\n\r\nlet description = \"Checking \";\r\n\r\nsetDescription( description );\r\n\r\nconst swrList = [];\r\n\r\nfor( const tFreq of freqList ) {\r\n\tawait sendCat(`F${vfo}${tFreq};`, false);\r\n\tawait txStart();\r\n\tawait delay(100);\r\n\tconst swr = await getSWR();\r\n\tswrList.push({freq: tFreq, swr });  \r\n\tawait txStop();\t\r\n\tsetDescription( description += \".\" );\r\n}\r\n\r\nawait revertSettings();\r\n\r\nlet output = swrList.map( v=> {\r\n\treturn `${Math.round(v.freq/100)/10}: ${v.swr}`\r\n})\r\n.join(\" | \");\r\n\r\nsetDescription( output );",
  "autoRunOnConnect": false,
  "autoRunPriority": 0,
  "autoLock": false,
  "runLocked": false
}

=== RhinoLance/figaro-community/script-library/band-floor.json
{
  "title": "Band floor",
  "description": "Tune to the bottom of the current band",
  "script": "const FREQ_STEP = 100; // 100Hz step, adjust as needed\r\nconst SCAN_SPEED = 100; // 100ms between frequency changes, adjust as needed\r\n\r\nlet freq =0;\r\nlet scanIntervalId;\r\nlet vfo;\r\n\r\n// array of bands' MHz and lowest frequencies in Hz\r\nconst bandFloors = [\r\n\t{MHz: 1, floor: 1800000},\r\n\t{MHz: 3, floor: 3500000},\r\n\t{MHz: 5, floor: 5351500},\r\n\t{MHz: 7, floor: 7000000},\r\n\t{MHz: 10, floor: 10100000},\r\n\t{MHz: 14, floor: 14000000},\r\n\t{MHz: 18, floor: 18068000},\r\n\t{MHz: 21, floor: 21000000},\r\n\t{MHz: 24, floor: 24890000},\r\n\t{MHz: 28, floor: 28000000},\r\n\t{MHz: 50, floor: 50000000}\r\n]\r\n\r\nconst getVFO = () => {\r\n\treturn sendCat(\"FR;\")\r\n\t.then( v => vfo = parseInt(v.substring(2)) == 0 ? \"A\" : \"B\");\r\n};\r\n\r\nconst initFreq = () =>{\r\n\treturn sendCat(`F${vfo};`)\r\n\t\t.then( v=> freq = parseInt(v.substring(2)));\r\n};\r\n\r\nconst setFreq = () => {\r\n\t\r\n\tconst bandFloor = Math.floor(freq / 1000000);\r\n\tconst band = bandFloors.find(b => b.MHz === bandFloor);\r\n\r\n\tfreq = band.floor;\r\n\tsendCat(`F${vfo}${freq};`, false);\r\n};\r\n\r\nconst runner = Promise.resolve()\r\n\t.then( getVFO )\r\n\t.then( initFreq )\r\n\t.then( setFreq );\r\n\t\r\n\ttask.waitUntil(runner);",
  "autoRunOnConnect": false,
  "autoRunPriority": 0,
  "autoLock": false,
  "runLocked": false
}

=== RhinoLance/figaro-community/script-library/swr-tune.json
{
  "title": "SWR Tune",
  "description": "Place the radio into SWR mode, and display the SWR",
  "script": "console.log(\"Tune script\");\r\n\r\nconst saveSettings = async () => {\r\n\t/*\r\n\r\n\tIF\r\n\t00021044020     +00000000006000000 \r\n\t00021044020\r\n\t-----\r\n\t+0000\r\n\t0000006000000 \r\n\t\r\n\t0-10 digits: IF frequency in Hz\t\t\t00021044020\r\n\t11-15 N/A (Spaces)\t\t\t\t\t\t-----\r\n\t16-20 RIT offset in Hz (signed)\t\t\t+0000\r\n\t21 RIT status (0=off, 1=on)\t\t \t\r\n\t22 XIT status (0=off, 1=on)\r\n\t23-25 N/A\r\n\t26 TX Status (0=RX, 1=TX)\r\n\t27 MODE\r\n\t28 RX VFO (0=A, 1=B)\r\n\t29 N/A\r\n\t30 Split status (0=off, 1=on)\r\n\t31-32 N/A\r\n\t33 N/A (Space)\r\n\t*/\r\n\r\n\tconst rawIF = (await sendCat(`IF;`)).substring(2);\r\n\tfreq = rawIF.substring(0,10);\r\n\tvfo = rawIF.substring(28,29) == \"0\" ? \"A\" : \"B\";\r\n\tmode = rawIF.substring(27,28);\r\n\r\n\tconsole.log(`Saved settings - Freq: ${freq}, VFO: ${vfo}, Mode: ${mode}`);\r\n}\r\n\r\nconst revertSettings = () => {\r\n\tsendCat(`MD${mode};`, false);\r\n};\r\n\r\nconst printSWR = async () => {\r\n\tconst raw = (await sendCat('SW;')).substring(2);\r\n\tlet val = raw / 100;\r\n\tprint( `${dispFreq}\\n${val.toFixed(1)}` );\r\n};\r\n\r\nconst getBand = (freq) => {\r\n\tconst band = Math.floor(freq / 100000);\r\n\treturn `${band} MHz`;\r\n};\r\n\r\nconst tuneSetup = async () => {\r\n\tawait saveSettings();\r\n};\r\n\r\nconst tuneStart = () => {\r\n\tsendCat('MD8;', false); // SWR\r\n};\r\n\r\nconst tuneStop = async () => {\r\n\tsendCat(`MD${mode};`, false);\r\n}\r\n\r\nconst tuneTeardown = () => {\r\n\ttask.clearInterval(interval);\r\n\trevertSettings();\r\n};\r\n\r\nconst getFirmwareVersion = async () => {\r\n\tconst versionText = await sendCat(\"VN;\");  // 1_04_003QMX;\r\n\tconst parts = versionText.split(\"_\");\r\n\tconst major = parseInt(parts[0].substring(2));\r\n\tconst minor = parseInt(parts[1]);\r\n\tconst patch = parseInt(parts[2].substring(0,3));\r\n\r\n\treturn [major,minor,patch];\r\n}\r\n\r\nconst isFirmwareOk = (fwVersion, checkVersion) => {\r\n\r\n\tconst invalidCheckVersion = () => {\r\n\t\tconsole.error( `Invalid firmware check version: ${checkVersion}`)\r\n\t};\r\n\r\n\tif( checkVersion.length < 3){\r\n\t\tinvalidCheckVersion();\r\n\t}\r\n\r\n\tfor( let cI=0; cI<fwVersion.length; cI++ ) {\r\n\t\tif( isNaN(checkVersion[cI])) {\r\n\t\t\tinvalidCheckVersion();\r\n\t\t}\r\n\t\tif( fwVersion[cI] < checkVersion[cI] ) return false;\r\n\t}\r\n\r\n\treturn true;\r\n}\r\n\r\nconst prerunCheck = async () => {\r\n\r\n\tconst fwVersion = await getFirmwareVersion();\r\n\tconst reqFw = [1,4,3];\r\n\tif( !isFirmwareOk(fwVersion, reqFw)) {\r\n\t\tsetDescription(\"ERROR: This script requires firmware >= \" + \r\n\t\t\treqFw.join(\".\"));\r\n\t\treturn false;\r\n\t}\r\n\r\n\treturn true;\r\n\r\n}\r\n\r\nlet interval, freq, vfo, mode, power, vol, dispFreq;\r\n\r\nif( !(await prerunCheck())) return;\r\n\r\nawait tuneSetup();\r\n\r\ndispFreq = getBand(freq);\r\ninterval = task.setInterval(printSWR, 500);\r\n\r\nawait tuneStart();\r\nawait pause('stop', '#D63031');\r\nawait tuneStop();\r\n\r\ntuneTeardown();",
  "autoRunOnConnect": false,
  "autoRunPriority": 0,
  "autoLock": false,
  "runLocked": false
}
